export { AboutComponent } from './About'
export { ContactComponent } from './Contact'
export { HomeComponent } from './Home'
export { Page404ErrorComponent } from './Page404error'
export { ShortsComponent } from './Shorts'
export { FilmComponent } from './Film'
export { FeaturesComponent } from './Features'
export { DocumentariesComponent } from './Documentaries'