#!/bin/bash
export AWS_AMPLIFY_AUTH_IDENTITYPOOLID=%_YOUR_VALUE_HERE_%
export AWS_AMPLIFY_AUTH_USERPOOLID=%_YOUR_VALUE_HERE_%
export AWS_AMPLIFY_AUTH_USERPOOL_WEBCLIENT_ID=%_YOUR_VALUE_HERE_%
export AWS_AMPLIFY_API_ENDPOINT=%_YOUR_VALUE_HERE_%
